#!/usr/bin/env python3
"""Check, and optionally write, the generation-ceiling table: how often generation reached the cap.

The 24-token cap scopes every result in the paper. A reader needs to know whether a model failed a
descriptor or simply ran out of room to write the arithmetic down, so the paper states the cap and
how often it binds. This script reads each run's own checkpoint (results/<run>.json.<cond>.ckpt),
which stores `max_new` and the per-item generated length, so the numbers cannot drift from the runs
they describe. It asserts the quantities that the methodology and appendix state in prose: the cap,
the worst full-condition ceiling rate, the full-condition median lengths, and the blind-condition
rate for Mistral-7B. With --emit it also writes outputs/tex/tabs/tab_ceiling.tex; the table itself
is not typeset in the paper.

Input: results/v41core_<tag>.json.{full,blind}.ckpt and results/v41pilot_gemma3_12b.json.{full,blind}.ckpt
(written by eval_factqa.py).

Usage:
  python gauge/make_ceiling_table.py [--check] [--emit]
"""
from __future__ import annotations
import argparse, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "outputs", "tex", "tabs", "tab_ceiling.tex")

# Display name -> run stem. Gemma's core run carries the v41pilot prefix; every other model carries
# v41core. Naming them explicitly keeps a rename from silently dropping a model from the table.
RUNS = [
    ("Phi-3.5-mini",   "v41core_phi35mini"),
    ("Mistral-7B",     "v41core_mistral7b"),
    ("Llama-3.1-8B",   "v41core_llama8b"),
    ("Gemma-3-12B",    "v41pilot_gemma3_12b"),
    ("Llama-3.1-70B",  "v41core_llama70b"),
]


def row(stem, cond):
    p = os.path.join(ROOT, "results", "%s.json.%s.ckpt" % (stem, cond))
    d = json.load(open(p))
    mn = d["max_new"]
    g = sorted(x for x in d["genlen"][cond] if x is not None)
    if not g:
        sys.exit("no generation lengths in %s" % p)
    return dict(max_new=mn, n=len(g), median=g[len(g) // 2],
                cap=100.0 * sum(1 for x in g if x >= mn) / len(g))


def build():
    rows = []
    for name, stem in RUNS:
        f, b = row(stem, "full"), row(stem, "blind")
        if f["max_new"] != b["max_new"]:
            sys.exit("%s: full and blind ran at different caps (%d vs %d)"
                     % (name, f["max_new"], b["max_new"]))
        rows.append((name, f, b))
    caps = {r[1]["max_new"] for r in rows}
    if len(caps) != 1:
        sys.exit("models ran at different generation caps %s; one table cannot describe them" % caps)
    cap = caps.pop()
    ns = {r[1]["n"] for r in rows} | {r[2]["n"] for r in rows}
    if len(ns) != 1:
        sys.exit("runs cover different question counts %s" % ns)
    n = ns.pop()

    L = []
    L.append("% GENERATED by gauge/make_ceiling_table.py -- do not edit by hand.")
    # Set tight: short caption, footnotesize body, [h] rather than [t] so that it does not float
    # onto a page of its own.
    L.append("\\begin{table}[h]")
    L.append("\\centering")
    L.append("\\caption{Generated length against the %d-token cap, over all %s questions per model "
             "and condition.}" % (cap, "{:,}".format(n).replace(",", "{,}")))
    L.append("\\label{tab:ceiling}")
    L.append("\\footnotesize")
    L.append("\\setlength{\\tabcolsep}{4pt}")
    L.append("\\begin{tabular}{lcccc}")
    L.append("\\toprule")
    L.append(" & \\multicolumn{2}{c}{full} & \\multicolumn{2}{c}{blind} \\\\")
    L.append("\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}")
    L.append("model & median & at cap & median & at cap \\\\")
    L.append("\\midrule")
    for name, f, b in rows:
        L.append("%s & %d & %.2f\\%% & %d & %.2f\\%% \\\\"
                 % (name, f["median"], f["cap"], b["median"], b["cap"]))
    L.append("\\bottomrule")
    L.append("\\end{tabular}")
    L.append("\\end{table}")
    return "\n".join(L) + "\n", rows, cap


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="kept for the build gate; checking is the default")
    ap.add_argument("--emit", action="store_true", help="also write the LaTeX table (not typeset by default)")
    a = ap.parse_args()
    tex, rows, cap = build()

    # The quantities the paper states in prose. If any moves, a sentence in the paper is wrong, and
    # this fails rather than letting prose and runs disagree. Compare on the rounded value: the prose
    # quotes two decimal places, and an exact-float comparison against a printed number fails on the
    # printed number itself.
    worst_full = max(r[1]["cap"] for r in rows)
    fmed = [r[1]["median"] for r in rows]
    mistral_blind = [r[2]["cap"] for r in rows if r[0] == "Mistral-7B"][0]
    others = [r[1]["cap"] for r in rows] + [r[2]["cap"] for r in rows if r[0] != "Mistral-7B"]
    print("cap %d | worst full at-cap %.2f%% | full medians %d to %d | Mistral blind %.2f%% | "
          "every other cell < %.2f%%" % (cap, worst_full, min(fmed), max(fmed),
                                         mistral_blind, max(others)))
    # The methodology section states: a median of 4 to 5 tokens, at most 1.88% of questions at the
    # cap, and a cap of 24 tokens.
    assert cap == 24, "methodology says 24 tokens, runs used %d" % cap
    assert round(worst_full, 2) <= 1.88, \
        "methodology says at most 1.88%% in the full condition, found %.2f%%" % worst_full
    assert (min(fmed), max(fmed)) == (4, 5), \
        "methodology says a full-condition median of 4 to 5 tokens, found %d to %d" \
        % (min(fmed), max(fmed))
    # The appendix states: Mistral-7B reaches that ceiling on 23.50% of blind questions, and every
    # other model and condition stays under 2%.
    assert round(mistral_blind, 2) == 23.50, \
        "appendix says Mistral-7B blind is 23.50%%, found %.2f%%" % mistral_blind
    assert max(others) < 2.0, \
        "appendix says every other cell stays under 2%%, found %.2f%%" % max(others)

    # The table is not typeset in the paper, which carries the worst case in one sentence instead.
    # This script stays as the check on those sentences. --emit writes the table anyway.
    if not a.emit:
        print("CHECK ONLY -- prose claims match the runs (table not typeset, see --emit)")
        return
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write(tex)
    print("wrote %s" % OUT)


if __name__ == "__main__":
    main()
