#!/usr/bin/env python3
"""Emit outputs/tex/tabs/tab_dissociation.tex: one set of answers, two decisions.

The Discussion argues that what survives the geometric null is an ordering and not a level. The
argument rests on three numbers per model, and the table puts them side by side: the same answers
produce the left column and the right ones.

Columns:
  exact gain  the headline statistic on the geometric families (results/v41_family_cis.json)
  rank gain   top-decile selection, positioned between a permutation of the truth (the floor, which
              carries no individual information) and the true values (the ceiling)
  count       the share of people placed above the population's true 75th percentile. The truth is
              25.0% in every setting, and so is a permutation, so any departure is error.

Cells above the unparsed threshold are excluded by score_dissociation.py and reported there.

Input: results/v41_dissociation.json (from score_dissociation.py) and results/v41_family_cis.json.
Output: outputs/tex/tabs/tab_dissociation.tex.

Usage:
  python gauge/make_dissociation_table.py [--check]
"""
from __future__ import annotations
import argparse, json, os, sys
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIS = os.path.join(ROOT, "results", "v41_dissociation.json")
FCI = os.path.join(ROOT, "results", "v41_family_cis.json")
OUT = os.path.join(ROOT, "outputs", "tex", "tabs", "tab_dissociation.tex")
GEO = {"gyration_km", "longest_jump", "max_distance", "total_distance"}
MODELS = [("Phi-3.5-mini", "phi35mini", "Phi-3.5"), ("Mistral-7B", "mistral7b", "Mistral-7B"),
          ("Llama-3.1-8B", "llama8b", "Llama-8B"), ("Gemma-3-12B", "gemma3_12b", "Gemma-12B"),
          ("Llama-3.1-70B", "llama70b", "Llama-70B")]


def build():
    d = json.load(open(DIS)); cells = d["cells"]; maxu = d["max_unparsed"]
    fci = json.load(open(FCI))
    rows, meta = [], {}
    for disp, key, short in MODELS:
        r = [v for k, v in cells.items() if k.startswith(disp + "|") and v["unparsed"] <= maxu]
        ex = [v["gain"] for k, v in fci.items()
              if isinstance(v, dict) and "gain" in v
              and k.split("|")[0] == key and k.split("|")[1] in GEO]
        rank = float(np.median([x["rank_gain"] for x in r]))
        nsig = sum(1 for x in r if x["rank_gain_ci"] and x["rank_gain_ci"][0] > 0)
        sh = [100 * x["share_above_model"] for x in r]
        meta[key] = dict(rank=rank, nsig=nsig, n=len(r))
        rows.append("%s & %+.3f & %+.3f & %d/%d & %.0f--%.0f \\\\"
                    % (short, float(np.median(ex)), rank, nsig, len(r), min(sh), max(sh)))

    L = ["% GENERATED by gauge/make_dissociation_table.py. Do not edit by hand.",
         "\\begin{table}[t]", "\\centering",
         "\\caption{Two decisions from one set of answers, on the four geometric families. Exact "
         "gain is normalized gain over the per-setting baseline. Rank gain positions top-decile selection between "
         "a permutation of the true values, which carries no information about any individual, and "
         "the true values themselves. The count is the share of people placed above the "
         "population's true 75th percentile, where both the truth and a permutation give 25\\%.}",
         "\\label{tab:dissociation}", "\\footnotesize",
         "\\setlength{\\tabcolsep}{4pt}",
         "\\begin{tabular}{lcccc}", "\\toprule",
         "model & exact gain & rank gain & CI${>}0$ & count (\\%) \\\\", "\\midrule"]
    L += rows
    L += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(L) + "\n", meta


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    tex, meta = build()
    # the two numbers the Discussion states in prose
    assert round(meta["llama70b"]["rank"], 3) == 0.204, \
        "Discussion says Llama-70B median rank gain +0.204, table gives %+.3f" % meta["llama70b"]["rank"]
    assert (meta["llama70b"]["nsig"], meta["llama70b"]["n"]) == (10, 20), \
        "Discussion says 10 of 20 intervals exclude zero, table gives %d of %d" % (
            meta["llama70b"]["nsig"], meta["llama70b"]["n"])
    print("asserts OK: Llama-70B +0.204, 10 of 20 intervals exclude zero")
    if a.check:
        if os.path.exists(OUT) and open(OUT).read() != tex:
            sys.exit("tab_dissociation.tex is stale; rerun gauge/make_dissociation_table.py")
        print("CHECK ONLY -- table matches the artifacts")
        return
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write(tex)
    print("wrote %s" % os.path.relpath(OUT, ROOT))


if __name__ == "__main__":
    main()
