#!/usr/bin/env python3
"""Emit outputs/tex/tabs/tab_program.tex: the program arm, per model and geometric family.

Each cell reads "expressions that reproduce the reference on 50 held-out records / expressions that
are correct on the model's own record", from results/program_equivalence.json. A per-family
table shows two points that a prose list hides. For Gemma-3-12B the programs hold on two of the four
families: radius of gyration and total distance have none. And the hold rate is not ordered by
capacity: Phi-3.5-mini keeps 49 of 50 while Llama-3.1-8B keeps none of 79.

The number of expressions that ran is kept separate from the number that were correct, because a
model that emits no runnable expression has not been shown to lack the descriptor, only to have
failed to write code. Mistral-7B is the case that matters: its well-formed rate is .063 in
results/scored_tool.json.

The script asserts the five per-model totals that the paper states.

Input: results/program_equivalence.json (from program_equivalence.py).
Output: outputs/tex/tabs/tab_program.tex.

Usage:
  python gauge/make_program_table.py [--check]
"""
from __future__ import annotations
import argparse, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "results", "program_equivalence.json")
OUT = os.path.join(ROOT, "outputs", "tex", "tabs", "tab_program.tex")

MODELS = [("phi35mini", "Phi-3.5"), ("mistral7b", "Mistral-7B"), ("llama8b", "Llama-8B"),
          ("gemma3_12b", "Gemma-12B"), ("llama70b", "Llama-70B")]
# Short headers, so that the table fits the column.
FAMS = [("gyration", "$r_g$"), ("max_distance", "max disp."),
        ("total_distance", "total dist."), ("longest_jump", "long. jump")]


def build():
    d = json.load(open(SRC))
    rows, totals = [], {}
    for mk, mname in MODELS:
        cells, t_here, t_eq = [], 0, 0
        for fk, _ in FAMS:
            v = d.get("%s|%s" % (mk, fk))
            if v is None:
                cells.append("--")
                continue
            t_here += v["right_here"]
            t_eq += v["equivalent"]
            # "0" carries information here and must not be an em-dash: it says the model wrote
            # expressions and none of them reproduced the reference.
            cells.append("%d/%d" % (v["equivalent"], v["right_here"]))
        totals[mk] = (t_eq, t_here)
        rows.append("%s & %s & %d/%d \\\\" % (mname, " & ".join(cells), t_eq, t_here))

    L = ["% GENERATED by gauge/make_program_table.py from results/program_equivalence.json.",
         "% Do not edit by hand.",
         "\\begin{table}[t]",
         "\\centering",
         "\\caption{Program arm. Each cell is expressions that reproduce the reference on 50 "
         "held-out records, over expressions correct on the model's own record. Gemma-12B holds on "
         "two of the four families, and the hold rate is not ordered by capacity: "
         "Phi-3.5 keeps 49 of 50 while Llama-8B keeps none of 79.}",
         "\\label{tab:program}",
         "\\footnotesize",
         "\\setlength{\\tabcolsep}{3pt}",
         "\\begin{tabular}{lccccc}",
         "\\toprule",
         "model & " + " & ".join(n for _, n in FAMS) + " & all \\\\",
         "\\midrule"]
    L += rows
    L += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(L) + "\n", totals, d


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    tex, totals, d = build()

    # The five totals the paper states in prose. If any moves, a sentence in the paper is wrong.
    want = {"llama70b": (1155, 1155), "gemma3_12b": (118, 118), "phi35mini": (49, 50),
            "llama8b": (0, 79), "mistral7b": (0, 0)}
    for mk, (eq, here) in want.items():
        assert totals[mk] == (eq, here), \
            "%s: paper says %d/%d, artifact gives %d/%d" % (mk, eq, here, *totals[mk])
    # The two claims the table exists to correct.
    g_hold = [f for f, _ in FAMS if d.get("gemma3_12b|%s" % f, {}).get("equivalent", 0) > 0]
    assert len(g_hold) == 2, "Gemma holds on %d families, not 2: %s" % (len(g_hold), g_hold)
    assert d["gemma3_12b|gyration"]["equivalent"] == 0, "Gemma gyration is no longer 0"
    print("totals match the paper for all five models")
    print("Gemma holds on exactly 2 of 4 families: %s" % g_hold)
    print("hold rate non-monotone: phi 49/50 = %.2f, llama8b 0/79 = %.2f"
          % (49 / 50, 0 / 79 if 79 else 0))

    if a.check:
        if os.path.exists(OUT) and open(OUT).read() != tex:
            sys.exit("tab_program.tex is stale; rerun gauge/make_program_table.py")
        print("CHECK ONLY -- table matches the artifact")
        return
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write(tex)
    print("wrote %s" % os.path.relpath(OUT, ROOT))


if __name__ == "__main__":
    main()
