#!/usr/bin/env python3
"""Check that every released module is logic-identical to the original it came from.

For each released file the checker parses it and the original, removes all docstrings and the
text of argparse help arguments, and compares the two syntax trees with ast.dump. Comments never
reach the syntax tree, so they are free to differ.

The only other differences allowed are string constants that are listed in STRING_EDITS below:
file-system path defaults, and printed or raised message text. A listed string must differ in the
tree exactly where the original has a different string. Any other difference fails the file.

Usage:
  python tools/check_ast_equivalence.py --orig-root PATH_TO_ORIGINAL_PROJECT
  python tools/check_ast_equivalence.py --selftest

Prints one PASS or FAIL line per file and exits 1 if any file fails. The original project is
needed only to run this check; the released code does not depend on it.
"""
from __future__ import annotations

import argparse
import ast
import os
import sys
import tempfile
import warnings

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)

# Released modules. Each lives in gauge/ and came from <orig-root>/scripts/ under the same name.
FILES: list[str] = [
    "continuous_metric.py", "crop_figure.py", "distributional_rung.py", "error_taxonomy.py",
    "eval_factqa.py", "expect_models.py", "export_v4.py", "family_cis.py", "make_appendix.py",
    "make_blind_decomposition.py", "make_ceiling_table.py", "make_cot_items.py",
    "make_dissociation_table.py", "make_figures.py", "make_frontier_figure.py",
    "make_ladder_figure.py", "make_nomobility.py", "make_program_table.py", "make_stripped.py",
    "make_subset.py", "make_tables.py", "make_templates.py", "multiplicity.py",
    "preflight_items.py", "program_equivalence.py", "run_frontier_probe.py",
    "score_blind_all_models.py", "score_compare.py", "score_control_ladder.py",
    "score_control_tolerance.py", "score_cot_budget.py", "score_dissociation.py",
    "score_frontier.py", "score_geomfix.py", "score_mitigation.py", "score_nomobility.py",
    "score_stripped.py", "score_templates.py", "score_tool.py", "score_whichK.py",
    "screen_degeneracy.py", "tally_compare.py", "tally_control.py", "tally_ladder.py",
    "tally_tool.py", "tally_v3.py", "tally_v4.py", "tally_v41.py", "tally_whichK.py",
    "tasks_compare.py", "tasks_control.py", "tasks_ladder.py", "tasks_tool.py", "tasks_v41.py",
    "tolerance_gate.py", "verify_v41_claims.py",
]

# file name -> list of (kind, released string). kind is "path" for a file-system path default or
# "msg" for text that is only printed or raised. The original string is read from the original file
# at check time, so nothing about the original is stored here.
STRING_EDITS: dict[str, list[tuple[str, str]]] = {
    "error_taxonomy.py": [
        ('msg', 'ABSTENTION, PER MODEL'),
    ],
    "expect_models.py": [
        ('msg', '\n    A partial set produces a confident but unrepresentative result.\n    Copy the missing runs into place, or pass --allow-partial to score anyway and have the\n    shortfall printed beside every number.'),
    ],
    "export_v4.py": [
        ('path', 'data/yjmob100k/yjmob100k-dataset1.csv.gz'),
    ],
    "family_cis.py": [
        ('msg', ' -- a five-model claim may not be made from a partial table. Copy the missing runs into place or correct the glob.'),
    ],
    "make_appendix.py": [
        ('path', 'gauge/tally_v41.py'),
        ('path', 'outputs/tex/tabs'),
        ('msg', '% GENERATED by gauge/make_appendix.py -- do not edit by hand.\n'),
    ],
    "make_blind_decomposition.py": [
        ('path', 'gauge/make_blind_decomposition.py'),
        ('msg', "Computed from the Gemma-3-12B core run. Its blind arm is at-cap 0.0%. Mistral-7B's blind arm is at-cap 23.5% and is NOT the source of this claim."),
    ],
    "make_ceiling_table.py": [
        ('path', 'outputs'),
        ('msg', '% GENERATED by gauge/make_ceiling_table.py -- do not edit by hand.'),
    ],
    "make_dissociation_table.py": [
        ('path', 'outputs'),
        ('msg', '% GENERATED by gauge/make_dissociation_table.py. Do not edit by hand.'),
        ('msg', 'tab_dissociation.tex is stale; rerun gauge/make_dissociation_table.py'),
    ],
    "make_figures.py": [
        ('path', 'outputs'),
        ('path', '~/.cache/gauge/fonts'),
    ],
    "make_frontier_figure.py": [
        ('path', 'gauge'),
        ('path', 'outputs'),
    ],
    "make_ladder_figure.py": [
        ('msg', 'fig_ladder.pdf missing; run gauge/make_ladder_figure.py'),
    ],
    "make_nomobility.py": [
        ('msg', ' -- run: python gauge/tally_v41.py --only-coord (the arm is built on the corrected-header coordinate items)'),
        ('msg', '  python gauge/eval_factqa.py --items '),
    ],
    "make_program_table.py": [
        ('path', 'outputs'),
        ('msg', '% GENERATED by gauge/make_program_table.py from results/v41_program_equivalence.json.'),
        ('msg', 'tab_program.tex is stale; rerun gauge/make_program_table.py'),
    ],
    "make_stripped.py": [
        ('msg', 'question differs beyond the total_distance substitution'),
        ('msg', ' items: same points in same order, no day/timeslot/record/mobility tokens, question changed only by the total_distance substitution, gold untouched'),
    ],
    "make_tables.py": [
        ('msg', 'STALE %s; rerun gauge/make_tables.py to regenerate'),
        ('path', 'outputs'),
        ('msg', '% GENERATED by gauge/make_tables.py from results/v41_family_cis.json. Do not edit by hand.\n\\begin{table*}[t]\n  \\centering\n  \\small\n  \\caption{Best normalized gain over the baseline that each model reaches on each descriptor\n  family, over every length at which that family exists: seven for distinct places per day and\n  recency, five for the geometric families, fewer for the longer windows. Bold marks a family whose\n  95\\% interval excludes the baseline at some length. No geometric family exceeds the baseline for any model at any length, while\n  every count and sequence family clears it for at least one.}\n  \\label{tab:main}\n  \\begin{tabular}{l'),
        ('path', 'survey'),
        ('msg', '% GENERATED by gauge/make_tables.py from survey/capability_coverage.md. Do not edit by hand.\n\\begin{table*}[t]\n  \\centering\n  \\footnotesize\n  \\setlength{\\tabcolsep}{3pt}\n  \\caption{Capabilities of twenty mobility and urban foundation models.\n  The first four columns are widely shared across these systems. No system emits a descriptor value\n  for an individual and none evaluates recovery of one, the gap this paper measures.}\n  \\label{tab:capability}\n  \\begin{tabular}{@{}lcccccc@{}}\n    \\toprule\n    System & \\makecell{Individual\\\\record} & \\makecell{Language\\\\interface} &\n    \\makecell{Raw location\\\\input} & \\makecell{Multiple\\\\tasks} &\n    \\makecell{Descriptor-valued\\\\output} & \\makecell{Recovery\\\\evaluated} \\\\\n    \\midrule\n'),
        ('msg', 'a published system now emits a descriptor value; the capability claim changed'),
        ('msg', 'the paper says 13 have no language interface; parsed '),
        ('msg', 'the paper says 15 cannot be asked; parsed '),
        ('msg', 'assert OK: counting rule re-derived from the survey table'),
        ('msg', '% GENERATED by gauge/make_tables.py from v41_distributional_rung.json + v41_family_cis.json.\n\\begin{table}[t]\n  \\centering\n  \\small\n  \\caption{Which of the three measurement levels each model-family-length cell occupies, over the seven families whose answers are magnitudes. The remaining fourteen return place identifiers, for which a distributional match and a rank correlation are not defined, and they carry no level below exact. '),
        ('msg', '% GENERATED by gauge/make_tables.py from results/v41_pilot_analysis.json.\n\\begin{table}[t]\n  \\centering\n  \\small\n  \\caption{Predictions about which descriptors survive which record lengths,\n  scored against the results. '),
        ('msg', ' and one was never built. The prediction for distinct places per day was\n  the decisive test and holds only at 70B.}\n  \\label{tab:prereg}\n  \\begin{tabular}{@{}lllll@{}}\n    \\toprule\n    & Family & Prediction & Observed & Verdict \\\\\n    \\midrule\n'),
    ],
    "multiplicity.py": [
        ('msg', 'family cells (main table)'),
        ('msg', 'representation probe'),
    ],
    "program_equivalence.py": [
        ('msg', 'coincidence on one record -- which is what the claim that the model knows the computation requires.'),
    ],
    "run_frontier_probe.py": [
        ('path', 'gauge'),
        ('msg', 'NOTE: %s not found; pass an index file with --subset. Falling back to a stratified\n      draw here would give a DIFFERENT item set than the open-weight runs scored.'),
    ],
    "score_blind_all_models.py": [
        ('path', 'gauge'),
    ],
    "score_control_ladder.py": [
        ('msg', 'DECOMPOSITION CONTROLS — gain with cluster-bootstrap CI over users\n'),
        ('msg', 'SCAFFOLD LADDER — gain with cluster-bootstrap CI over users\n'),
    ],
    "score_dissociation.py": [
        ('path', 'gauge'),
    ],
    "score_frontier.py": [
        ('path', 'gauge'),
    ],
    "score_tool.py": [
        ('msg', 'VERDICT — does the model know the computation it cannot perform?\n'),
    ],
    "score_whichK.py": [
        ('msg', '3,782 distinct users appear, none in more than 0.59% of items.\n'),
    ],
    "tally_v41.py": [
        ('msg', 'the prompt cap binds; it would select items, not only shorten them'),
        ('msg', '\nNEXT: check the cells for degeneracy before using this file (gauge/screen_degeneracy.py on a pilot run).'),
    ],
    "tally_whichK.py": [
        ('msg', '\nGATE 0 — PROMPT CAP. Candidates rejected for exceeding '),
        ('msg', '\nGATE 3 — CLUSTER VARIABLE'),
    ],
    "verify_v41_claims.py": [
        ('msg', 'absence detect @16'),
        ('msg', 'absence detect @512'),
        ('msg', 'retrieve p10 @512'),
        ('msg', 'retrieve p70 @512'),
        ('msg', 'rho gyration_km @32'),
        ('msg', 'rho gyration_km @512'),
        ('msg', 'rho longest_stay @512'),
        ('msg', 'rho day_distinct @16'),
        ('msg', 'rho window_w16 @32'),
        ('msg', 'rho window_w16 @512'),
    ],
}

ARG_CALLS_HELP = {"add_argument", "add_parser", "add_argument_group", "add_subparsers"}
ARG_CALLS_TEXT = {"ArgumentParser", "add_parser", "add_argument_group", "add_subparsers"}


def _call_name(call: ast.Call) -> str:
    f = call.func
    if isinstance(f, ast.Attribute):
        return f.attr
    if isinstance(f, ast.Name):
        return f.id
    return ""


def _is_string_statement(stmt: ast.stmt) -> bool:
    return (isinstance(stmt, ast.Expr) and isinstance(stmt.value, ast.Constant)
            and isinstance(stmt.value.value, str))


def normalise(tree: ast.AST) -> ast.AST:
    """Remove docstrings, other bare string statements and argparse help text, in place.

    A string that stands alone as a statement does nothing when the program runs, whether it is
    the docstring or a second block of text below it, so none of them are compared."""
    for node in ast.walk(tree):
        for field in ("body", "orelse", "finalbody"):
            stmts = getattr(node, field, None)
            if isinstance(stmts, list) and stmts and all(isinstance(x, ast.stmt) for x in stmts):
                kept = [x for x in stmts if not _is_string_statement(x)]
                if len(kept) != len(stmts):
                    stmts[:] = kept or [ast.Pass()]
        if isinstance(node, ast.Call):
            name = _call_name(node)
            for kw in node.keywords:
                if (kw.arg == "help" and name in ARG_CALLS_HELP) or (
                        kw.arg in ("description", "epilog", "usage") and name in ARG_CALLS_TEXT):
                    kw.value = ast.Constant(value="")
    return tree


def _walk_compare(a, b, allowed: dict[str, str], used: list, bad: list, where: str) -> None:
    """Compare two trees node by node. A differing string constant is accepted only when the
    released value is in `allowed`; it is then replaced in the released tree by the original."""
    if type(a) is not type(b):
        bad.append(f"{where}: {type(a).__name__} became {type(b).__name__}")
        return
    if isinstance(a, ast.AST):
        if isinstance(a, ast.Constant):
            if a.value != b.value or type(a.value) is not type(b.value) or a.kind != b.kind:
                if isinstance(a.value, str) and isinstance(b.value, str) and b.value in allowed:
                    used.append((allowed[b.value], a.value, b.value))
                    b.value = a.value
                else:
                    bad.append(f"{where}: constant {a.value!r:.80} became {b.value!r:.80}")
            return
        for field in a._fields:
            _walk_compare(getattr(a, field, None), getattr(b, field, None), allowed, used, bad,
                          f"{where}.{field}@{getattr(a, 'lineno', '?')}")
        return
    if isinstance(a, list):
        if len(a) != len(b):
            bad.append(f"{where}: {len(a)} items became {len(b)}")
            return
        for i, (x, y) in enumerate(zip(a, b)):
            _walk_compare(x, y, allowed, used, bad, f"{where}[{i}]")
        return
    if a != b:
        bad.append(f"{where}: {a!r} became {b!r}")


def compare_sources(orig_src: str, rel_src: str, edits: list[tuple[str, str]] | None = None):
    """Return (ok, used, problems). `used` lists (kind, original, released) for each accepted
    string edit."""
    allowed = {s: k for k, s in (edits or [])}
    try:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")        # old sources may hold invalid escape sequences
            a = normalise(ast.parse(orig_src))
            b = normalise(ast.parse(rel_src))
    except SyntaxError as exc:
        return False, [], [f"syntax error: {exc}"]
    used: list = []
    bad: list = []
    _walk_compare(a, b, allowed, used, bad, "module")
    if not bad and ast.dump(a) != ast.dump(b):
        bad.append("ast.dump differs after normalisation")
    declared = {s for _, s in (edits or [])}
    unused = declared - {u[2] for u in used}
    for s in sorted(unused):
        bad.append(f"listed string edit never matched: {s!r:.80}")
    return not bad, used, bad


def check_tree(orig_root: str, rel_root: str, files: list[str],
               string_edits: dict[str, list[tuple[str, str]]], out=sys.stdout) -> int:
    failures = 0
    gdir = os.path.join(rel_root, "gauge")
    present = sorted(f for f in os.listdir(gdir) if f.endswith(".py")) if os.path.isdir(gdir) else []
    for extra in sorted(set(present) - set(files)):
        print(f"FAIL gauge/{extra}: released file is not in the checker's file list", file=out)
        failures += 1
    for name in files:
        rel = os.path.join(rel_root, "gauge", name)
        orig = os.path.join(orig_root, "scripts", name)
        if not os.path.exists(rel):
            print(f"FAIL gauge/{name}: missing from the release", file=out)
            failures += 1
            continue
        if not os.path.exists(orig):
            print(f"FAIL gauge/{name}: original not found at {orig}", file=out)
            failures += 1
            continue
        with open(orig, encoding="utf-8") as fh:
            osrc = fh.read()
        with open(rel, encoding="utf-8") as fh:
            rsrc = fh.read()
        ok, used, bad = compare_sources(osrc, rsrc, string_edits.get(name))
        if ok:
            extra = f" ({len(used)} listed string edit{'s' if len(used) != 1 else ''})" if used else ""
            print(f"PASS gauge/{name}{extra}", file=out)
            for kind, o, r in used:
                print(f"       {kind}: {o!r:.100}  ->  {r!r:.100}", file=out)
        else:
            failures += 1
            print(f"FAIL gauge/{name}", file=out)
            for p in bad[:8]:
                print(f"       {p}", file=out)
    return failures


# ----------------------------------------------------------------------------- self-test
_BASE = '''#!/usr/bin/env python3
"""Original docstring with internal words."""
import argparse


def total(xs):
    """Sum a list."""
    acc = 0
    for x in xs:
        acc += x + 1   # trailing comment
    return acc


def main():
    ap = argparse.ArgumentParser(description="original description")
    ap.add_argument("--n", type=int, default=3, help="original help")
    ap.add_argument("--out", default="results/out.json")
    a = ap.parse_args()
    if a.n < 5:
        print("original message", total(range(a.n)))


if __name__ == "__main__":
    main()
'''


def selftest() -> int:
    cases = []

    def case(name, new_src, want_ok, edits=None, want_used=0):
        cases.append((name, new_src, want_ok, edits, want_used))

    case("identical file", _BASE, True)
    case("docstrings rewritten", _BASE.replace("Original docstring with internal words.", "New text.")
         .replace("Sum a list.", "Add the items."), True)
    case("docstring added to a function that had none",
         _BASE.replace("def main():", 'def main():\n    """Entry point."""'), True)
    case("docstring removed", _BASE.replace('    """Sum a list."""\n', ""), True)
    case("second text block under the module docstring", _BASE.replace(
        'import argparse', '"""A second block of text."""\nimport argparse'), True)
    case("a string statement that is not documentation is still ignored only if bare",
         _BASE.replace("    return acc", '    "stray"\n    return acc'), True)
    case("comments changed", _BASE.replace("# trailing comment", "# other words")
         .replace("def main", "# a new comment line\ndef main"), True)
    case("argparse help and description changed", _BASE.replace("original help", "new help")
         .replace("original description", "new description"), True)
    case("planted logic change: operator", _BASE.replace("acc += x + 1", "acc += x - 1"), False)
    case("planted logic change: number", _BASE.replace("a.n < 5", "a.n < 6"), False)
    case("planted logic change: comparison", _BASE.replace("a.n < 5", "a.n <= 5"), False)
    case("planted logic change: default", _BASE.replace("default=3", "default=4"), False)
    case("extra statement", _BASE.replace("    return acc", "    acc += 0\n    return acc"), False)
    case("renamed function", _BASE.replace("def total", "def add_all").replace("total(range", "add_all(range"),
         False)
    case("unlisted string change", _BASE.replace("original message", "new message"), False)
    case("unlisted path change", _BASE.replace("results/out.json", "results/other.json"), False)
    case("listed path change accepted", _BASE.replace("results/out.json", "results/other.json"), True,
         edits=[("path", "results/other.json")], want_used=1)
    case("listed message change accepted", _BASE.replace("original message", "new message"), True,
         edits=[("msg", "new message")], want_used=1)
    case("listed edit hides a logic change", _BASE.replace("original message", "new message")
         .replace("acc += x + 1", "acc += x + 2"), False, edits=[("msg", "new message")])
    case("listed edit that matches nothing", _BASE, False, edits=[("msg", "never present")])
    case("syntax error", _BASE + "\ndef broken(:\n", False)

    bad = 0
    for name, src, want_ok, edits, want_used in cases:
        ok, used, problems = compare_sources(_BASE, src, edits)
        good = (ok == want_ok) and (not want_ok or len(used) == want_used)
        print(f"  [{'ok ' if good else 'BAD'}] {name}: checker said {'PASS' if ok else 'FAIL'}"
              f", expected {'PASS' if want_ok else 'FAIL'}")
        bad += 0 if good else 1

    # tree-level cases: a missing file and an unlisted extra file must both fail
    with tempfile.TemporaryDirectory() as tmp:
        orig = os.path.join(tmp, "orig")
        rel = os.path.join(tmp, "rel")
        os.makedirs(os.path.join(orig, "scripts"))
        os.makedirs(os.path.join(rel, "gauge"))
        for root, sub in ((orig, "scripts"), (rel, "gauge")):
            with open(os.path.join(root, sub, "m.py"), "w") as fh:
                fh.write(_BASE)
        with open(os.path.join(rel, "gauge", "extra.py"), "w") as fh:
            fh.write("x = 1\n")
        import io
        buf = io.StringIO()
        n_fail = check_tree(orig, rel, ["m.py", "gone.py"], {}, out=buf)
        good = n_fail == 2 and "PASS gauge/m.py" in buf.getvalue()
        print(f"  [{'ok ' if good else 'BAD'}] tree check: one pass, one missing file, one unlisted file "
              f"-> {n_fail} failures (expected 2)")
        bad += 0 if good else 1
    print("SELFTEST " + ("PASS" if not bad else f"FAIL ({bad} wrong verdicts)"))
    return 1 if bad else 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--orig-root", help="root of the original project (its scripts/ directory)")
    ap.add_argument("--release-root", default=REPO, help="root of this repository (default: parent of tools/)")
    ap.add_argument("--selftest", action="store_true", help="run the checker's own tests and exit")
    a = ap.parse_args()
    if a.selftest:
        return selftest()
    if not a.orig_root:
        ap.error("--orig-root is required unless --selftest is given")
    failures = check_tree(a.orig_root, a.release_root, FILES, STRING_EDITS)
    total = len(FILES)
    if failures:
        print(f"FAILED: {failures} problem(s) across {total} files")
        return 1
    print(f"ALL {total} files pass")
    return 0


if __name__ == "__main__":
    sys.exit(main())
